### ISSUE TITLE
Unable to Install Spinnaker - 

### ISSUE THREAD

**Issue by ramesher** [in4it/spinnaker-course#11]
Hello,

When I run 5 script and get the below error on Ubuntu 20.04 (LTS) x64. Can you please suggest?

Setting spinnaker home to /home
Reading package lists...
Building dependency tree...
Reading state information...
W: --force-yes is deprecated, use one of the options starting with --allow instead.
E: Unable to locate package spinnaker-igor
! ERROR Error encountered running script. See above output for more
  details.
=====================
ubuntu@spinnaker-course:~/spinnaker-course/scripts$ sudo apt update
Hit:1 https://download.docker.com/linux/ubuntu focal InRelease
Hit:2 http://mirrors.digitalocean.com/ubuntu focal InRelease
Hit:3 http://ppa.launchpad.net/chris-lea/redis-server/ubuntu focal InRelease
Ign:4 https://dl.bintray.com/spinnaker-releases/debians focal InRelease
Hit:5 http://ppa.launchpad.net/openjdk-r/ppa/ubuntu focal InRelease
Hit:6 http://mirrors.digitalocean.com/ubuntu focal-updates InRelease
Err:7 https://dl.bintray.com/spinnaker-releases/debians focal Release
  Could not handshake: The TLS connection was non-properly terminated. [IP: 35.157.253.39 443]
Hit:8 http://mirrors.digitalocean.com/ubuntu focal-backports InRelease
Hit:9 https://repos-droplet.digitalocean.com/apt/droplet-agent main InRelease
Hit:10 http://security.ubuntu.com/ubuntu focal-security InRelease
Reading package lists... Done
E: The repository 'https://dl.bintray.com/spinnaker-releases/debians focal Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
=======================================

**Comment by wardviaene** [comment]
This indeed a current issue in the Spinnaker non-kubernetes install. It'll be fixed in the next release, see https://github.com/spinnaker/spinnaker/issues/6568#issuecomment-1076007898

Only alternative currently is to use a helm chart with kubernetes to install spinnaker, until the next release is out (for example https://github.com/OpsMx/spinnaker-helm)

**Comment by ramesher** [comment]
Hello,

Do you mean I should have Kubernetes cluster and use spinnaker helm chat to install spinnaker right?

Thanks,
Ramesh

**Comment by wardviaene** [comment]
Correct, or you can wait some time until the next release comes out and then you can install it without kubernetes. Spinnaker has 2 ways to install it, with or without kubernetes. The first way to install it without is currently not working, but should be fixed in the next Spinnaker release.

**Comment by ramesher** [comment]
I was able to install spinnaker using helm chat in kubernetes. Looks like it is hal service created cluster IP. Which document or video to access spinnaker UI?

Thanks,
Ramesh

**Comment by wardviaene** [comment]
We currently don't have any videos explaining the Kubernetes-Spinnaker install. Best to use the Q&A on Udemy to reach out to us. How you can access a service depends on your kubernetes install. You can expose a NodePort and connect on there, or try with a loadbalancer/ingress.
