### ISSUE TITLE
! ERROR Unexpected exception: java.lang.IndexOutOfBoundsException:

### ISSUE THREAD

**Issue by jayamurugans** [in4it/spinnaker-course#2]
Hi 

I am getting ! ERROR Unexpected exception: java.lang.IndexOutOfBoundsException: while running spinnaker deploy after changing rosco.yml. Can someone help me? I am trying baking AWS VM but that gives me the ! ERROR Unexpected exception: java.lang.IndexOutOfBoundsException:.

**Comment by wardviaene** [comment]
This often means that you're entering invalid yaml. Check the indentation and whether you're correct yaml (you can use yamllint.com to check).
