### ISSUE TITLE
Unable to connect <ip>:8084

### ISSUE THREAD

**Issue by alexcorr** [in4it/spinnaker-course#4]
I followed the installation scripts (1 to 6) trying to setup Spinnaker In a VM hosted by Digital Ocean. Everything goes fine but when I try to connect to Spinnaker using a browser accessing address <ip>:9000 it displays the Hello Message and while it tries to authenticate it shows the message unable to connect to the server at 104.248.220.241:8084. 
Inspecting the console window on the browser it shows the following message:
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://<ip>:8084/auth/user. (Reason: CORS request did not succeed).[Learn More]

Trying a telnet localhost 8084 on the host where spinnaker is installed, I get:
Unable to connect to remote host: Connection refused.

And netstat --listen generates the following result:
ubuntu@spinnaker:~/spinnaker-course/scripts$ netstat --listen
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State      
tcp        0      0 *:9000                  *:*                     LISTEN     
tcp        0      0 *:ssh                   *:*                     LISTEN     
tcp        0      0 localhost:9090          *:*                     LISTEN     
tcp6       0      0 localhost:http-alt      [::]:*                  LISTEN     
tcp6       0      0 localhost:8083          [::]:*                  LISTEN     
tcp6       0      0 [::]:ssh                [::]:*                  LISTEN     
tcp6       0      0 localhost:8087          [::]:*                  LISTEN     
tcp6       0      0 localhost:omniorb       [::]:*                  LISTEN     
tcp6       0      0 localhost:8089          [::]:*                  LISTEN     
tcp6       0      0 [::]:8064               [::]:*                  LISTEN     
Active UNIX domain sockets (only servers)
Proto RefCnt Flags       Type       State         I-Node   Path
unix  2      [ ACC ]     STREAM     LISTENING     16325    /run/user/0/systemd/private
unix  2      [ ACC ]     SEQPACKET  LISTENING     8567     /run/udev/control
unix  2      [ ACC ]     STREAM     LISTENING     8562     /run/systemd/private
unix  2      [ ACC ]     STREAM     LISTENING     8573     /run/lvm/lvmpolld.socket
unix  2      [ ACC ]     STREAM     LISTENING     8574     /run/systemd/journal/stdout
unix  2      [ ACC ]     STREAM     LISTENING     8658     /run/lvm/lvmetad.socket
unix  2      [ ACC ]     STREAM     LISTENING     12054    /run/uuidd/request
unix  2      [ ACC ]     STREAM     LISTENING     30101    @/containerd-shim/moby/4bf28dd114801eacf92e48e54a429614ba868e40483ed09abad7ddfac569fb4a/shim.sock
unix  2      [ ACC ]     STREAM     LISTENING     12058    /var/lib/lxd/unix.socket
unix  2      [ ACC ]     STREAM     LISTENING     12055    /run/snapd.socket
unix  2      [ ACC ]     STREAM     LISTENING     12056    /run/snapd-snap.socket
unix  2      [ ACC ]     STREAM     LISTENING     12057    /var/run/dbus/system_bus_socket
unix  2      [ ACC ]     STREAM     LISTENING     12059    /run/acpid.socket
unix  2      [ ACC ]     STREAM     LISTENING     14238    @ISCSIADM_ABSTRACT_NAMESPACE
unix  2      [ ACC ]     STREAM     LISTENING     28435    /run/containerd/containerd.sock
unix  2      [ ACC ]     STREAM     LISTENING     28567    /var/run/docker.sock
unix  2      [ ACC ]     STREAM     LISTENING     29630    /var/run/docker/metrics.sock
unix  2      [ ACC ]     STREAM     LISTENING     29749    /run/docker/libnetwork/e2691b733d89938be2202e31622379dae3b9

Spinnaker version installed is 1.9.5.

Any clues on how can I get it running?

**Comment by manoj3004** [comment]
i am also facing same issue ..any help will be highly appreciated

**Comment by khaledj1** [comment]
hi guys,
I have the same problem but I solved finally
there is a problem in repo scripts
in 5-deploy-spinnaker.sh:
change this line:
`sudo apt-get -y install redis`
with this line:
```
sudo apt update && sudo apt upgrade -y
sudo apt-get install redis-server
```

**Comment by wardviaene** [comment]
I changed the code today to include the install of redis. apt-get update was indeed missing which can be useful for some systems (worked for me without). I updated the script.

-Edward
